version: "2.4"

services:
  iroha_node_0:
    image: hyperledger/iroha:latest
    expose: 
      - 10001
    ports:
      - 50051:50051
    environment:
      - "KEY=node0"
      - "IROHA_POSTGRES_HOST=postgres_1"
    volumes:
      - blockstore_0:/tmp/block_store
      - $PWD/config0:/opt/iroha_data
    depends_on:
      - postgres_1
    networks:
      - iroha-network
    restart: always

  iroha_node_1:
    image: hyperledger/iroha:latest
    expose: 
      - 10001
    ports:
      - 50052:50051
    environment:
      - "KEY=node1"
      - "IROHA_POSTGRES_HOST=postgres_2"
    volumes:
      - blockstore_1:/tmp/block_store
      - $PWD/config1:/opt/iroha_data
    depends_on:
      - postgres_2
    networks:
      - iroha-network
    restart: always


  iroha_node_2:
    image: hyperledger/iroha:latest
    expose: 
      - 10001
    ports:
      - 50053:50051
    environment:
      - "KEY=node2"
      - "IROHA_POSTGRES_HOST=postgres_3"
    volumes:
      - blockstore_2:/tmp/block_store
      - $PWD/config2:/opt/iroha_data
    depends_on:
      - postgres_2
    networks:
      - iroha-network
    restart: always


  iroha_node_3:
    image: hyperledger/iroha:latest
    expose: 
      - 10001
    ports:
      - 50054:50051
    environment:
      - "KEY=node3"
      - "IROHA_POSTGRES_HOST=postgres_4"
    volumes:
      - blockstore_3:/tmp/block_store
      - $PWD/config3:/opt/iroha_data
    depends_on:
      - postgres_4
    networks:
      - iroha-network
    restart: always
  
  postgres_1:
    image: postgres:9.5
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - 5432
    networks:
      - iroha-network
    restart: always
  
  postgres_2:
    image: postgres:9.5
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - 5432
    networks:
      - iroha-network
    restart: always

  postgres_3:
    image: postgres:9.5
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - 5432
    networks:
      - iroha-network
    restart: always


  postgres_4:
    image: postgres:9.5
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - 5432
    networks:
      - iroha-network
    restart: always

volumes:
  blockstore_0:
  blockstore_1:
  blockstore_2:
  blockstore_3:

networks:
  iroha-network: